feat: 재고 감소 로직 및 재고 회복 로직 작성
Gosrock/DuDoong-Backend pull request #165
Opened 2023-01-20 18:20 UTC by sanbonai06

## 개요
- close #143 

## 작업사항
- 재고 감소와 재고 회복 로직을 작성했습니다.
- 도메인 이벤트를 받아서 처리합니다.
- 도메인 이벤트 핸들러를 통해 redissonLock을 걸어 놓은 도메인 서비스에 작성한 로직으로 들어가 실행됩니다.
- 추가로 티켓 상품 도메인에 티켓 재고에 따른 밸리데이션 처리를 추가했습니다.
- @cofls6581 해당 로직 참고해서 쿠폰 관련 처리 로직도 해주시면 됩니다.

## 변경로직
- 발급 티켓에 orderUuid 컬럼이 추가되었습니다.
- 해당 컬럼을 통해 티켓 예매 취소 및 환불 로직이 동작합니다.

2023-01-20 18:22 UTC, ImNM requested changes

2023-01-20 18:22 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
> +
0보다 작을 때는 요?

2023-01-20 18:28 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
> +    }
롤백이름보다는 그냥 재고 추가하는게?
보편적인 이름 같아유

2023-01-20 18:48 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
> +
해결

2023-01-20 18:48 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
> +    }
해결

2023-01-21 05:06 UTC, ImNM approved these changes

2023-01-21 05:06 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
> +    }
공급량 체크 하는 것도 좋을 것 같아요
공급량보다 넘지않게..?

2023-01-21 05:06 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/handlers/WithDrawOrderEventHandler.java
> +    public void handleRegisterUserEvent(WithDrawOrderEvent withDrawOrderEvent) {
요기 메서드 명 바꿔야 할듯 해요!

2023-01-21 05:06 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +                });
흐음 드는 생각이 요기는 issuedTicket 만 delete 해주는데 
저희근데 delete 말고 soft 딜리트나 티켓 상태를 취소등으로 표현 해줘야해요!

아무튼 issuedTicket 이랑 issuedTicket옵션 답변 엔티티
둘을 cascade 옵션 놓고 생명주기 같게 관리하면 어떨까 싶긴해요

현 상황은  issuedTicket옵션답변 레포지토리가 필요한건 아니니깐..?

2023-01-21 05:06 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/adaptor/IssuedTicketAdaptor.java
> +    }
요기!!

2023-01-21 05:07 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +                });
> 아무튼 issuedTicket 이랑 issuedTicket옵션 답변 엔티티 둘을 cascade 옵션 놓고 생명주기 같게 관리하면 어떨까 싶긴해요
> 
> 현 상황은 issuedTicket옵션답변 레포지토리가 필요한건 아니니깐..?

요부분은 그 이슈티켓 생성하는 부분 말한거였어요!
보니깐 issuedTicket옵션답변 레포지토리로 save 치길래
구냥 한번에 issuedTicket 레포지토리로 세이브 치는?

2023-01-21 05:10 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +                });
```java
    public void createIssuedTicket(
            TicketItem ticketItem, List<CreateIssuedTicketDTO> createIssuedTicketDTOs) {
        createIssuedTicketDTOs.forEach(
                dto -> {
                    CreateIssuedTicketResponse responseDTO =
                            IssuedTicket.orderLineItemToIssuedTickets(dto);
                    issuedTicketAdaptor.saveAll(responseDTO.getIssuedTickets());
                   // 이부분을 없앨수있지 않을까...?
                    issuedTicketOptionAnswerAdaptor.saveAll(
                            responseDTO.getIssuedTicketOptionAnswers());
                });
    }


```

2023-01-21 06:10 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
> +    }
확인했습니다.

2023-01-21 06:11 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/handlers/WithDrawOrderEventHandler.java
> +    public void handleRegisterUserEvent(WithDrawOrderEvent withDrawOrderEvent) {
아 이거 컨플릭트 수정하다가 잘못 바꿨네요 수정하겠습니다.

2023-01-21 06:11 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +                });
넵

2023-01-21 06:11 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/adaptor/IssuedTicketAdaptor.java
> +    }
소프트 딜리트 전략 사용위해서 발급 티켓 상태 더 추가하겠습니당

2023-01-21 07:10 UTC, ImNM reviewed
@sanbonai06

2023-01-21 07:10 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +        issuedTickets.forEach(
민준님 이거 
생각해보니깐 티켓생성이나 환불 할때
같은 재고 정보를 가지고 하는거니
락이 같아야 될것같아요
따라서 LockName 파라미터가 `티켓재고관리` 나 `티켓` 등의 동일한 락 이름을 가져야 할것 같아요

2023-01-21 07:22 UTC, kim-wonjin approved these changes
LGTM🌿👍

2023-01-21 07:51 UTC, merged