test : issuedTicketDomainService 테스트 코드 작성
Gosrock/DuDoong-Backend pull request #354
Opened 2023-02-14 17:00 UTC by sanbonai06

## 개요
- close #316

## 작업사항
- 발급 티켓 관련 서비스들에 관한 테스트 코드를 작성했습니다.
- 아직 동시성 테스트에 관한 코드는 작성하지 못했습니다.
- 따로 이슈 파서 작업하도록 하겠습니다.

## 변경로직
- 발급 티켓 생성하는 코드 부분이 뎁스를 한 번 더 들어가는 것이 불필요하고 테스트 코드 짜는데에 있어서 불편해서 orderToIssuedTicket에서 담당하는 코드를 조금씩 분산해서 리팩토링 했습니다.

2023-02-14 17:12 UTC, ImNM requested changes
-https://sonarcloud.io/component_measures?id=Gosrock_DuDoong-Backend&pullRequest=354&metric=new_coverage&view=list

코드 커버리지 가셔서
테스트 안된 부분?한번 보시는것도 좋은것같아요

어떤부분이 커버가 안됏는지 다나오니깐!

2023-02-14 17:12 UTC, ImNM commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +                                    ticketItem.reduceQuantity(1L);
order lien item 내부에 
한개의 아이템 quantity만 존재하는게 아닙니다!

한 오더라인에 한 아이템은 맞지만
여러개 ( 옵션 응답이 같은 아이템 ) 가있을수 있어용...

2023-02-14 17:13 UTC, sanbonai06 commented on DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/service/IssuedTicketDomainService.java
> +                                    ticketItem.reduceQuantity(1L);
오호

2023-02-15 04:12 UTC, gengminy approved these changes
테스트 코드 구현 참고하겠습니다 👍

2023-02-15 04:44 UTC, ImNM approved these changes
LGTM!

2023-02-15 06:21 UTC, merged